# Generated by Django 3.1.7 on 2021-06-16 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=25, null=True)),
                ('profile_image', models.ImageField(default='profil_dafault.jpg', upload_to='')),
                ('department', models.CharField(choices=[('R&D', 'R&D'), ('Human Resource', 'Human Resource'), ('Financing', 'Financing'), ('board of Directors', 'board of Directors')], max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('meet_links', models.URLField(max_length=100, null=True)),
                ('meet_location', models.CharField(choices=[('Office', 'Office'), ('Online', 'Online')], max_length=10)),
                ('start_date', models.DateTimeField(blank=True)),
                ('finish_date', models.DateTimeField(blank=True)),
                ('finished', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('creater_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management.account')),
            ],
        ),
        migrations.CreateModel(
            name='MeetParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.meet')),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
