# Generated by Django 3.2.4 on 2021-06-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0004_chatgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
